apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: ToolchainConfig
metadata:
  name: config
spec:
  host:
    deactivation:
      deactivationDomainsExcluded: "@excluded.com"
    environment: "e2e-tests"
    notifications:
      durationBeforeNotificationDeletion: "5s"
    tiers:
      durationBeforeChangeTierRequestDeletion: "5s"
    toolchainStatus:
      toolchainStatusRefreshTime: "1s"
  members:
    default:
      autoscaler:
        deploy: true
        bufferMemory: "50Mi"
        bufferReplicas: 2
      memberStatus:
        refreshPeriod: "1s"
      toolchainCluster:
        healthCheckPeriod: "5s"
