apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: onboarding-perfapp
type: Opaque
stringData:
  client-id: REPLACE_ME
  client-secret: REPLACE_ME
  cookie-secret: REPLACE_ME
  github-org: REPLACE_ME
  github-team: ""
